login_admitad_store:
    path: /admitad-store/
    defaults: { _controller: AdmitadUserBundle:Login:admitadStoreLogin }

login_admitad_oauth:
    path: /admitad-oauth/
    defaults: { _controller: AdmitadUserBundle:Login:admitadOAuthLogin }

login_admitad_oauth_check:
    path: /admitad-oauth/check
    defaults: { _controller: AdmitadUserBundle:Login:admitadOAuthLoginCheck }
