services:
    admitad_user.manager:
        class: Admitad\UserBundle\Manager\Manager
        arguments: [@doctrine]

    admitad_user.expired_token_listener:
        class: Admitad\UserBundle\EventListener\KernelListener
        arguments: [@security.context, @admitad_user.manager, @router]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


    admitad_user.authentication.provider:
        class: Admitad\UserBundle\Security\Authentication\Provider\AdmitadProvider
        arguments: [@security.user_checker, @admitad_user.manager]
        public: false

    admitad_user.authentication.listener.oauth:
        class:  Admitad\UserBundle\Security\Firewall\OAuthListener
        calls:
            - [setManager, [@admitad_user.manager]]
            - [setRouter, [@router]]
        parent: security.authentication.listener.abstract
        public: false
        abstract: true

    admitad_user.authentication.listener.signed_request:
        class:  Admitad\UserBundle\Security\Firewall\SignedRequestListener
        calls:
            - [setManager, [@admitad_user.manager]]
        parent: security.authentication.listener.abstract
        public: false
        abstract: true
